### ISSUE TITLE
configurator fails on changed path to endpoint config file

### ISSUE THREAD

**Issue by olberger** [nre-learning/syringe#107]
Running with antidote-selfmedicate, and trying to perform lesson 19, I get failures on configurator:
```
  configurator:
    Container ID:  docker://3d7039326ff9919b146eeb2a7074d960e77af181a96a6d06e310f38895fe9d9b
    Image:         antidotelabs/configurator
    Image ID:      docker-pullable://antidotelabs/configurator@sha256:222830b087fccc0e9f505315c8ed45edbf66d2cca0553e372340ed3d157286d2
    Port:          <none>
    Host Port:     <none>
    Command:
      /configure.py
      antidote
      antidotepassword
      junos
      22
      10.100.251.196
      /antidote/lessons/lesson-19/stage1/configs/vqfx1.txt
    State:          Terminated
      Reason:       Error
      Exit Code:    1

and:
./kubectl logs config-vqfx1-hmfvk -n 19-xbknat4682q3cj6r-ns
/usr/local/lib/python3.7/site-packages/paramiko/kex_ecdh_nist.py:39: CryptographyDeprecationWarning: encode_point has been deprecated on EllipticCurvePublicNumbers and will be removed in a future version. Please use EllipticCurvePublicKey.public_bytes to obtain both compressed and uncompressed point encoding.
  m.add_string(self.Q_C.public_numbers().encode_point())
/usr/local/lib/python3.7/site-packages/paramiko/kex_ecdh_nist.py:96: CryptographyDeprecationWarning: Support for unsafe construction of public numbers from encoded data will be removed in a future version. Please use EllipticCurvePublicKey.from_encoded_point
  self.curve, Q_S_bytes
/usr/local/lib/python3.7/site-packages/paramiko/kex_ecdh_nist.py:111: CryptographyDeprecationWarning: encode_point has been deprecated on EllipticCurvePublicNumbers and will be removed in a future version. Please use EllipticCurvePublicKey.public_bytes to obtain both compressed and uncompressed point encoding.
  hm.add_string(self.Q_C.public_numbers().encode_point())
NAPALM didn't catch this exception. Please, fill a bugfix on https://github.com/napalm-automation/napalm/issues
Don't forget to include this traceback.
Traceback (most recent call last):
  File "/configure.py", line 30, in <module>
    template_object = env.get_template(config_file)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python3.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python3.7/site-packages/jinja2/loaders.py", line 187, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: vqfx1.txt

```
But, AFAICT, the path should now be /antidote/lessons/fundamentals/lesson-19-restapis/stage1/configs/vqfx1.txt and not  /antidote/lessons/lesson-19/stage1/configs/vqfx1.txt

The culprit looks like https://github.com/nre-learning/syringe/blob/master/scheduler/jobs.go#L99

**Comment by Mierdin** [comment]
Yup, this is a problem. I'm going to work on a fix that maps lesson directories to `/antidote`, so we will only have to update the curriculum once to `cd` to that, rather than keep updating all of the referenced paths every time we want to restructure the curriculum.
